name: flutter_papertrail_alt
description: Elevate your app development experience with Flutter Paper Trail. Seamlessly integrate advanced logging and real-time monitoring into your Flutter project. Swiftly identify and prioritize issues with enhanced logging, customizable outputs, and error notifications. 
version: 0.0.3

homepage: https://github.com/kuntal811/flutter_papertrail_alt
dependencies:
  meta: ^1.8.0
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterPaperTrailAltPlugin
      android:
        package: com.kuntal.flutterpapertrail
        pluginClass: FlutterPaperTrailAltPlugin

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.0.0"
